package com.szfp.pos.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.szfp.pos.model.LoginRecord;
import com.szfp.pos.model.PosRecord;

import com.szfp.pos.greendao.LoginRecordDao;
import com.szfp.pos.greendao.PosRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginRecordDaoConfig;
    private final DaoConfig posRecordDaoConfig;

    private final LoginRecordDao loginRecordDao;
    private final PosRecordDao posRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginRecordDaoConfig = daoConfigMap.get(LoginRecordDao.class).clone();
        loginRecordDaoConfig.initIdentityScope(type);

        posRecordDaoConfig = daoConfigMap.get(PosRecordDao.class).clone();
        posRecordDaoConfig.initIdentityScope(type);

        loginRecordDao = new LoginRecordDao(loginRecordDaoConfig, this);
        posRecordDao = new PosRecordDao(posRecordDaoConfig, this);

        registerDao(LoginRecord.class, loginRecordDao);
        registerDao(PosRecord.class, posRecordDao);
    }
    
    public void clear() {
        loginRecordDaoConfig.clearIdentityScope();
        posRecordDaoConfig.clearIdentityScope();
    }

    public LoginRecordDao getLoginRecordDao() {
        return loginRecordDao;
    }

    public PosRecordDao getPosRecordDao() {
        return posRecordDao;
    }

}
